"""Автогенерация имён базовых станций: «Базовая станция {город}»."""

from __future__ import annotations

import random

BASE_STATION_CITY_POOL = [
    "Бердск",
    "Томск",
    "Казань",
    "Сочи",
    "Псков",
    "Тула",
    "Омск",
    "Вологда",
    "Суздаль",
    "Кострома",
    "Владимир",
    "Ярославль",
    "Рязань",
    "Курск",
    "Брянск",
    "Смоленск",
    "Тверь",
    "Калуга",
    "Орёл",
    "Тамбов",
    "Пенза",
    "Саратов",
    "Астрахань",
    "Элиста",
    "Грозный",
    "Махачкала",
    "Владикавказ",
    "Нальчик",
    "Черкесск",
    "Майкоп",
    "Анапа",
    "Геленджик",
    "Ейск",
    "Таганрог",
    "Белгород",
    "Липецк",
    "Тобольск",
    "Сургут",
    "Норильск",
    "Якутск",
    "Хабаровск",
    "Благовещенск",
    "Петропавловск",
    "Южно-Сахалинск",
    "London",
    "Boston",
    "Denver",
    "Seattle",
    "Portland",
    "Austin",
    "Chicago",
    "Madison",
    "Burlington",
    "Oslo",
    "Bergen",
    "Helsinki",
    "Tampere",
    "Kyoto",
    "Osaka",
    "Sapporo",
    "Nara",
    "Melbourne",
    "Adelaide",
    "Perth",
    "Quebec",
    "Halifax",
    "Munich",
    "Dresden",
    "Leipzig",
    "Salzburg",
    "Zurich",
    "Geneva",
    "Lyon",
    "Nantes",
    "Toulouse",
    "Valencia",
    "Seville",
    "Porto",
    "Coimbra",
    "Dublin",
    "Galway",
    "Reykjavik",
]


def generate_base_station_name(rng: random.Random | None = None) -> str:
    r = rng or random
    return f"Базовая станция {r.choice(BASE_STATION_CITY_POOL)}"
